// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dcqmbvucslwgnslxdnor.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRjcW1idnVjc2x3Z25zbHhkbm9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMTgxNjQsImV4cCI6MjA2NDY5NDE2NH0.Hx7DXyfIrp6ET3mNE517ojxrZCV8yabeBS9uzVL7Vho";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);